# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sunil Kumar
email: sunilsrix@gmail.com
description: "A constant quest to learn every day, every hour and everyminute.
Technology is an integral part of my life and it reflects in almost every facets
of life."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.sunilsrikumar.com" # the base hostname & protocol for your site
twitter_username: sunilsrikumar
github_username:  sunilsrikumar

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/

# Discuss
disqus_shortname: "sunilsrikumar"
